platform :ios, '11.0'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFingerprintAuth', :path => '../../node_modules/capacitor-fingerprint-auth'
  # Do not delete
end
